version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build-app:
    docker:
      - image: circleci/node:15.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  node-tests:
    jobs:
      - build-app
