version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build-app:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn install
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build-docker:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # Enabling this requires paid CircleCI plan
          version: 19.03.13
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/my-website-v2:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/my-website-v2:$TAG

  create-infra:
    working_directory: ~/project/infra/aws
    docker:
      - image: botagar/ansible-aws-cli:0.1.3
    steps:
      - checkout:
          path: ~/project
      - run: pwd
      - run: ls -l
      - run: cat control.sh
      - run: sh control.sh -a create -p my-website -e dev

workflows:
  infra:
    jobs:
      - create-infra:
          context:
            - AWS
  # node-tests:
  #   jobs:
  #     - build-app

  # docker:
  #   jobs:
  #     - build-docker:
  #         context:
  #           - Docker
